### PR TITLE
Feat: Added all components to doc site

### PR DESCRIPTION
**Pull request by Jaynil1611**
- Added all components to the [documentation ](https://mind-ui.netlify.app/) site
- Fixed importing css classes from the [component-library](https://mind-ui-library.netlify.app/)

### CODE REVIEW

**Review by vinaybajjuri58 — CHANGES_REQUESTED** [review]
Hey Jaynil 
The component library and docs site are good
I would suggest 3 changes in desktop view :
1.Add a code snippet so that user can know how to make use of components
2.Make the navigation bars responsive 
3.Removing the Home button on desktop view
Suggestions in mobile view:
Positioning of nav toggler
adding a Navlink to the logo 
Fix the scrolling part in mobile view

**Review by Aravindan07 — CHANGES_REQUESTED** [review]
1. Contrast issues in MIndUi Description.
2. Give padding and change colors of badges.
3. Change the colors on alert component just a suggestion!
4. Change the cursor to pointer for floating action buttons also remove outline from icon buttons.
5. Fix the overflow text in card.
6. Change the close modal button text to white.
6. Change the label on input components.
7. Change the cursor to pinter in toast close icon
8. Add margin around the hamburger icon in mobile screens.
9. Remove flex-basis in cards .
10. Change the width to 100% in buttons div for mobile screens.

**Review by Aravindan07 — APPROVED** [review]
Everything is fine for me. You can merge this branch.

**Review by vinaybajjuri58 — APPROVED** [review]
Everything is fine you can merge now.

**Comment by khusharth** [comment]
- Wherever you are using the primary color use white text with it instead of grey.
- For alerts stick to using red, green, yellow shades for error, success, and warning respectively.
- No need for secondary color / components,
- You can have outlined button instead of secondary. 
- For card change color to white and text as secondary color.
- Change the card-examples container bg to white (Don't use #fff use slightly darker shade). 
- Add one more image in Rounded Image . 
- FOr Input Textbox label you should change from primary color to using black.
- Can add the logo in Nav https://mind-ui.netlify.app/nav
- For Modal you can use same color as that of Cards.
- (to do later): Add a cross sign.
- Add code snippets for https://mind-ui.netlify.app/typography

**Comment by Jaynil1611** [comment]
@khusharth I have accommodated all the suggestions

**Pull request merged**
